version: '3.4'

services:

  django:
    restart: always
    container_name: django
    env_file:
      - ./django/mainapp/.env
    build:
      context: ./django/
      dockerfile: Dockerfile
    command: python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "7990:8000"
    
    networks:
      - external_net

  frontend:
    restart: always
    build: 
      context: ./myapp/
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - django
    networks:
      - external_net

networks:
  external_net:
    external: true