# Generated by Django 4.2.7 on 2024-03-21 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "testNames_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testNames",
                        to="dataprocesses.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refLink", models.TextField()),
                ("refYear", models.TextField()),
                ("refFinderEmail", models.TextField()),
                ("refTitle", models.TextField()),
                ("refPub", models.TextField()),
                ("refVol", models.TextField()),
                ("refIssue", models.TextField()),
                ("refPages", models.TextField()),
                ("refAuthors", models.TextField()),
                ("refType", models.TextField()),
                (
                    "references_id",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="dataprocesses.name",
                    ),
                ),
            ],
        ),
    ]
