version: '3.4'

services:
  django:
    restart: always
    container_name: django
    networks:
      - proxy_net
        
    env_file:
      - ./mainapp/.env
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn mainapp.wsgi --bind 0.0.0.0:7990
    ports:
      - "7990:7990"
   
    

networks:
 proxy_net:
   external: true
  
  