version: '3.4'

services:
  django:
    restart: always
    container_name: django
    
    env_file:
      - ./mainapp/.env
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn mainapp.wsgi --bind 10.100.2.13:7990
    ports:
      - "7990:7990"
   
    

networks:
 proxy_net:
   external: true
  
  